GTI_WebCore/Controllers/MobController.cs
using GTI_WebCore.Interfaces;
using GTI_WebCore.Models;
using GTI_WebCore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace GTI_WebCore.Controllers {

    [Route("Mob/Details")]
    public class MobController : Controller {
        private readonly IEmpresaRepository _empresaRepository;

        public MobController(IEmpresaRepository empresaRepository) {
            _empresaRepository = empresaRepository;
        }

        [HttpGet]
        public ViewResult Details() {
            return View();
        }

        [HttpPost]
        public ViewResult Details(EmpresaDetailsViewModel model) {
            int _codigo = 0;
            bool _existeCod = false;
            EmpresaDetailsViewModel empresaDetailsViewModel = new EmpresaDetailsViewModel();

            if (model.Inscricao != null) {
                _codigo = Convert.ToInt32(model.Inscricao);
                if(_codigo>=100000 && _codigo<210000) //Se estiver fora deste intervalo nem precisa checar se a empresa existe
                    _existeCod = _empresaRepository.Existe_Empresa_Codigo(_codigo);
            } else {
                if (model.CnpjValue != null) {
                    string _cnpj = model.CnpjValue;
                    bool _valida = Functions.ValidaCNPJ(_cnpj); //CNPJ válido?
                    if (_valida) {
                        _codigo = _empresaRepository.Existe_Empresa_Cnpj(_cnpj);
                        if (_codigo > 0)
                            _existeCod = true;
                    } else {
                        empresaDetailsViewModel.ErrorMessage = "Cnpj inválido.";
                        return View(empresaDetailsViewModel);
                    }
                } else {
                    if (model.CpfValue != null) {
                        string _cpf = model.CpfValue;
                        bool _valida = Functions.ValidaCpf(_cpf); //CPF válido?
                        if (_valida) {
                            _codigo = _empresaRepository.Existe_Empresa_Cpf(_cpf);
                            if (_codigo > 0)
                                _existeCod = true;

                        } else {
                            empresaDetailsViewModel.ErrorMessage = "Cpf inválido.";
                            return View(empresaDetailsViewModel);
                        }
                    }
                }
            }

            if (_existeCod) {
                Mobiliario mobiliario = _empresaRepository.GetEmpresaDetail(_codigo);
                empresaDetailsViewModel.Mobiliario = mobiliario;
                empresaDetailsViewModel.ErrorMessage = "";
            } else {
                empresaDetailsViewModel.ErrorMessage = "Empresa não cadastrada.";
            }
            return View(empresaDetailsViewModel);
        }


    }
}

GTI_WebCore/Views/Mob/Details.cshtml
@model GTI_WebCore.ViewModels.EmpresaDetailsViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Detalhe de uma empresa";
}



<label style="color:brown;font-size:16px;font-style:italic">Detalhes de uma empresa</label>
<br />

<form asp-controller="Mob" enctype="multipart/form-data" method="post" onsubmit="return ValidateForm()" asp-action="Details" class="mt-3">
    <div class="form-group row">
        <label asp-for="Inscricao"> </label>
        <div class="col-sm-10">
            <input asp-for="Inscricao" id="codigo" class="form-control" style="max-width:100px;max-height:25px;overflow:auto;" onKeyPress="return formata(this, '§§§§§§', event)" onchange="ClearError()">
        </div>
    </div>

    <div class="form-group row align-items-lg-baseline">
        CPF:&nbsp; <input type="radio" required asp-for="CpfCnpjLabel" id="cpfCheck" value="cpf" name="doc" checked="checked" onclick="radioCheck()" />
        &nbsp;CNPJ:&nbsp;  <input type="radio" required asp-for="CpfCnpjLabel" id="cnpjCheck" value="cnpj" name="doc" onclick="radioCheck()" />
        &nbsp;<input asp-for="CpfValue" id="cpfTxt" class="form-control" style="max-width:200px;max-height:25px;" onKeyPress="return formata(this, '§§§.§§§.§§§-§§', event)" onchange="ClearError()" placeholder="Digite o nº do CPF">
        &nbsp;<input asp-for="CnpjValue" id="cnpjTxt" class="form-control" style="max-width:200px;max-height:25px;display:none" onKeyPress="return formata(this, '§§.§§§.§§§/§§§§-§§', event)" onchange="ClearError()" placeholder="Digite o nº do CNPJ">
    </div>
    <br />
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-success"> Consultar</button>
        </div>
    </div>
    <div class="form-group row">
        <label class="text-danger" id="errorLabel"></label>
    </div>
</form>

@if (Model != null) {
    if (Model.Mobiliario == null) {
        <div class="form-group row">
            <label class="text-danger" id="errorLabel">@Model.ErrorMessage</label>
        </div>
    } else {
        <tr>
            <td>
                @Model.Mobiliario.Razaosocial
            </td>
        </tr>
    }
}


@section scripts{

    <script type="text/javascript">
        function radioCheck() {
            document.getElementById('cnpjTxt').value = "";
            document.getElementById('cpfTxt').value = "";
            if (document.getElementById('cpfCheck').checked) {
                document.getElementById('cpfTxt').style.display = 'block';
            }
            else {
                document.getElementById('cpfTxt').style.display = 'none';
            }
            if (document.getElementById('cnpjCheck').checked) {
                document.getElementById('cnpjTxt').style.display = 'block';
            }
            else {
                document.getElementById('cnpjTxt').style.display = 'none';
            }
        }

        function ValidateForm() {
            var _cod = document.getElementById('codigo').value;
            var _cpf = document.getElementById('cpfTxt').value;
            var _cnpj = document.getElementById('cnpjTxt').value;

            if ((_cod == "" || parseInt(_cod) == 0) && _cpf == "" && _cnpj == "") {
                document.getElementById('errorLabel').innerHTML = "Digite ao menos um dos campos!";
                return false;
            }
            else {
                if (parseInt(_cod) > 0 && (_cpf != "" || _cnpj != "")){
                    document.getElementById('errorLabel').innerHTML = "Digite a inscrição municipal ou o Cpf ou o CNPJ!";
                    return false;
                } else {
                    return true;
                }
            }
        }

        function ClearError() {
            document.getElementById('errorLabel').innerHTML = "";
        }

    </script>
}